import { getServiceSupabase } from './supabase';
import { getStarSign, getCompatibility, StarSign } from './starsigns';

/** Why the file was opened. Decides which questionnaire the entry shows. */
export type FileType = 'dating' | 'safety';

export const FILE_TYPES: FileType[] = ['dating', 'safety'];

export interface HisFile {
  id?: string;
  user_id?: string;
  file_type?: FileType;
  nickname: string;
  full_name?: string;
  phone?: string;
  /** Generated by Postgres from `phone`. Read-only — never send it back. */
  phone_normalized?: string | null;
  date_of_birth?: string;
  star_sign?: string;
  safety_score?: string;
  report_id?: string;
  report_data?: Record<string, unknown>;
  status?: string;
  where_we_met?: string;
  meetup_location?: string;
  met_on_app?: string;
  met_date?: string;
  first_date_location?: string;
  first_date_date?: string;
  first_date_paid?: string;
  gifts?: string[];
  icks?: string[];
  accurate_salary?: string;
  generosity_rating?: string;
  his_finsta?: string;
  notes?: string;
  compatibility_score?: number;
  compatibility_summary?: string;
  researched_at?: string;
}

export interface UserProfile {
  user_id: string;
  email: string;
  date_of_birth?: string;
  star_sign?: string;
}

export interface VerityWrapped {
  id?: string;
  user_id?: string;
  year: number;
  total_searches?: number;
  total_saved?: number;
  green_count?: number;
  yellow_count?: number;
  red_count?: number;
  most_active_month?: string;
  most_common_app?: string;
  most_common_ick?: string;
  average_generosity?: string;
  star_sign_breakdown?: Record<string, number>;
  status_breakdown?: Record<string, number>;
  headline?: string;
  share_token?: string;
  is_public?: boolean;
}

export async function getUserProfile(userId: string): Promise<UserProfile | null> {
  const sb = getServiceSupabase();
  const { data, error } = await sb.from('user_profiles').select('*').eq('user_id', userId).maybeSingle();
  if (error) throw error;
  return data ?? null;
}

export async function upsertUserProfile(userId: string, email: string, updates: Partial<UserProfile>): Promise<UserProfile | null> {
  const sb = getServiceSupabase();
  const starSign = updates.date_of_birth ? getStarSign(updates.date_of_birth) : undefined;
  const row = { user_id: userId, email, ...updates, ...(starSign ? { star_sign: starSign } : {}) };
  const { data, error } = await sb.from('user_profiles').upsert(row, { onConflict: 'user_id' }).select().single();
  if (error) throw error;
  return data ?? null;
}

export async function getHisFiles(userId: string): Promise<HisFile[]> {
  const sb = getServiceSupabase();
  const { data } = await sb.from('his_files').select('*').eq('user_id', userId).order('researched_at', { ascending: false });
  return data ?? [];
}

export async function getHisFile(userId: string, id: string): Promise<HisFile | null> {
  const sb = getServiceSupabase();
  const { data } = await sb.from('his_files').select('*').eq('user_id', userId).eq('id', id).single();
  return data ?? null;
}

/**
 * Mirrors the `phone_normalized` generated column in Postgres. Keep the two in
 * step: the column is what the unique index enforces, this is what decides
 * whether we update instead of insert.
 */
export function normalizePhone(phone?: string | null): string | null {
  const digits = (phone ?? '').replace(/\D/g, '');
  if (!digits) return null;
  if (digits.length === 11 && digits.startsWith('1')) return digits.slice(1);
  return digits;
}

function normalizeName(name?: string | null): string {
  return (name ?? '').trim().replace(/\s+/g, ' ').toLowerCase();
}

/**
 * The same man saved twice is one file, not two. Phone is the reliable key —
 * it is what the search was run on. Entries created by hand may have no phone,
 * so those fall back to an exact name match, which is deliberately narrow:
 * merging two different people is worse than showing one entry twice.
 */
export async function findDuplicateHisFile(userId: string, file: HisFile): Promise<HisFile | null> {
  const sb = getServiceSupabase();
  const phone = normalizePhone(file.phone);

  if (phone) {
    const { data } = await sb.from('his_files')
      .select('*')
      .eq('user_id', userId)
      .eq('phone_normalized', phone)
      .order('researched_at', { ascending: true })
      .limit(1);
    return data?.[0] ?? null;
  }

  const names = [normalizeName(file.full_name), normalizeName(file.nickname)].filter(Boolean);
  if (names.length === 0) return null;

  // Filtered here rather than in the query: names contain commas and quotes,
  // which are PostgREST filter syntax. A personal vault is small enough.
  const { data } = await sb.from('his_files')
    .select('*')
    .eq('user_id', userId)
    .is('phone_normalized', null)
    .order('researched_at', { ascending: true });

  return (data ?? []).find((row: HisFile) =>
    names.includes(normalizeName(row.full_name)) || names.includes(normalizeName(row.nickname))
  ) ?? null;
}

/** Fields a re-save may fill in but must never overwrite once the user has set them. */
const USER_OWNED_FIELDS: (keyof HisFile)[] = [
  'nickname', 'full_name', 'phone', 'date_of_birth', 'status', 'his_finsta', 'notes',
  'where_we_met', 'meetup_location', 'met_on_app', 'met_date',
  'first_date_location', 'first_date_date', 'first_date_paid',
  'accurate_salary', 'generosity_rating',
];

function isEmpty(value: unknown): boolean {
  return value === null || value === undefined || (typeof value === 'string' && value.trim() === '');
}

export interface SaveResult {
  file: HisFile | null;
  /** True when the save landed on an entry that already existed. */
  merged: boolean;
}

/**
 * The saved report behind a His File entry.
 *
 * A report used to live only in the tab that generated it, in sessionStorage,
 * so "View report" from His File worked until the tab closed and then said
 * "Report not found" forever. The row already had a report_data column; it
 * simply was never written or read.
 */
export async function getReportByReportId(
  userId: string,
  reportId: string,
): Promise<Record<string, unknown> | null> {
  const sb = getServiceSupabase();
  const { data } = await sb
    .from('his_files')
    .select('report_data')
    .eq('user_id', userId)
    .eq('report_id', reportId)
    .maybeSingle();
  return (data?.report_data as Record<string, unknown> | undefined) ?? null;
}

export async function saveHisFile(userId: string, file: HisFile): Promise<SaveResult> {
  const sb = getServiceSupabase();

  const starSign = file.date_of_birth ? getStarSign(file.date_of_birth) : undefined;

  let compatScore: number | undefined;
  let compatSummary: string | undefined;

  if (starSign) {
    const profile = await getUserProfile(userId);
    if (profile?.star_sign) {
      const compat = getCompatibility(starSign, profile.star_sign as StarSign);
      compatScore = compat.score;
      compatSummary = compat.summary;
    }
  }

  const row: Record<string, unknown> = {
    ...file,
    user_id: userId,
    ...(starSign ? { star_sign: starSign } : {}),
    ...(compatScore !== undefined ? { compatibility_score: compatScore, compatibility_summary: compatSummary } : {}),
    researched_at: file.researched_at ?? new Date().toISOString(),
  };

  // Generated column — Postgres rejects any attempt to write it.
  delete row.phone_normalized;

  if (file.id) {
    const { data, error } = await sb.from('his_files').update(row).eq('id', file.id).eq('user_id', userId).select().single();
    if (error) throw error;
    return { file: data ?? null, merged: false };
  }

  const existing = await findDuplicateHisFile(userId, file);

  if (existing) {
    // Saving the same man again refreshes the report he is attached to and
    // fills the blanks. It does not undo anything the user has typed since.
    const patch: Record<string, unknown> = {
      researched_at: row.researched_at,
      ...(file.report_id ? { report_id: file.report_id, safety_score: file.safety_score } : {}),
      ...(file.report_data ? { report_data: file.report_data } : {}),
      ...(starSign ? { star_sign: starSign } : {}),
      ...(compatScore !== undefined ? { compatibility_score: compatScore, compatibility_summary: compatSummary } : {}),
      // An explicit choice in the save dialog wins — it was made seconds ago.
      ...(file.file_type ? { file_type: file.file_type } : {}),
    };

    for (const field of USER_OWNED_FIELDS) {
      if (isEmpty(existing[field]) && !isEmpty(file[field])) patch[field] = file[field];
    }

    const { data, error } = await sb.from('his_files')
      .update(patch).eq('id', existing.id!).eq('user_id', userId).select().single();
    if (error) throw error;
    return { file: data ?? null, merged: true };
  }

  delete row.id;
  const { data, error } = await sb.from('his_files').insert(row).select().single();
  if (error) throw error;
  return { file: data ?? null, merged: false };
}

export async function deleteHisFile(userId: string, id: string): Promise<boolean> {
  const sb = getServiceSupabase();
  const { error } = await sb.from('his_files').delete().eq('id', id).eq('user_id', userId);
  return !error;
}

export async function backfillCompatibility(userId: string, userSign: StarSign): Promise<void> {
  const sb = getServiceSupabase();
  const { data: files } = await sb.from('his_files').select('id, star_sign').eq('user_id', userId);
  if (!files?.length) return;
  for (const file of files) {
    if (!file.star_sign) continue;
    const compat = getCompatibility(file.star_sign as StarSign, userSign);
    await sb.from('his_files')
      .update({ compatibility_score: compat.score, compatibility_summary: compat.summary })
      .eq('id', file.id)
      .eq('user_id', userId);
  }
}

export async function generateWrapped(userId: string, year: number): Promise<VerityWrapped | null> {
  const sb = getServiceSupabase();

  const startOf = `${year}-01-01T00:00:00.000Z`;
  const endOf = `${year + 1}-01-01T00:00:00.000Z`;

  const { data: files } = await sb
    .from('his_files')
    .select('*')
    .eq('user_id', userId)
    .gte('researched_at', startOf)
    .lt('researched_at', endOf);

  if (!files || files.length === 0) return null;

  const green = files.filter((f: HisFile) => f.safety_score === 'green').length;
  const yellow = files.filter((f: HisFile) => f.safety_score === 'yellow').length;
  const red = files.filter((f: HisFile) => f.safety_score === 'red').length;

  const monthCounts: Record<string, number> = {};
  files.forEach((f: HisFile) => {
    if (f.researched_at) {
      const m = new Date(f.researched_at).toLocaleString('en-US', { month: 'long' });
      monthCounts[m] = (monthCounts[m] ?? 0) + 1;
    }
  });
  const mostActiveMonth = Object.entries(monthCounts).sort((a, b) => b[1] - a[1])[0]?.[0] ?? null;

  // Dating-only metrics. A marketplace safety check has no app, no icks and no
  // one who picked up the bill, so counting those files would drag every
  // average toward nothing.
  const datingFiles = files.filter((f: HisFile) => (f.file_type ?? 'dating') === 'dating');

  const appCounts: Record<string, number> = {};
  datingFiles.forEach((f: HisFile) => {
    if (f.met_on_app) appCounts[f.met_on_app] = (appCounts[f.met_on_app] ?? 0) + 1;
  });
  const mostCommonApp = Object.entries(appCounts).sort((a, b) => b[1] - a[1])[0]?.[0] ?? null;

  const ickCounts: Record<string, number> = {};
  datingFiles.forEach((f: HisFile) => {
    (f.icks ?? []).forEach((ick: string) => {
      ickCounts[ick] = (ickCounts[ick] ?? 0) + 1;
    });
  });
  const mostCommonIck = Object.entries(ickCounts).sort((a, b) => b[1] - a[1])[0]?.[0] ?? null;

  const genOrder = ['cheap', 'average', 'generous', 'spoils me'];
  const genFiles = datingFiles.filter((f: HisFile) => f.generosity_rating);
  const avgGenScore = genFiles.length
    ? Math.round(genFiles.reduce((s: number, f: HisFile) => s + (genOrder.indexOf(f.generosity_rating!) + 1), 0) / genFiles.length)
    : 0;
  const avgGenerosity = avgGenScore > 0 ? genOrder[avgGenScore - 1] : null;

  const signCounts: Record<string, number> = {};
  files.forEach((f: HisFile) => {
    if (f.star_sign) signCounts[f.star_sign] = (signCounts[f.star_sign] ?? 0) + 1;
  });

  const statusCounts: Record<string, number> = {};
  files.forEach((f: HisFile) => {
    if (f.status) statusCounts[f.status] = (statusCounts[f.status] ?? 0) + 1;
  });

  const topDomain = red > green && red > yellow ? 'caution' : green > yellow ? 'well' : 'mixed results';
  const headline = `You researched ${files.length} men in ${year} and came out with ${topDomain}.`;

  const shareToken = Math.random().toString(36).slice(2) + Date.now().toString(36);

  const wrapped: VerityWrapped = {
    user_id: userId,
    year,
    total_searches: files.length,
    total_saved: files.length,
    green_count: green,
    yellow_count: yellow,
    red_count: red,
    most_active_month: mostActiveMonth ?? undefined,
    most_common_app: mostCommonApp ?? undefined,
    most_common_ick: mostCommonIck ?? undefined,
    average_generosity: avgGenerosity ?? undefined,
    star_sign_breakdown: signCounts,
    status_breakdown: statusCounts,
    headline,
    share_token: shareToken,
    is_public: false,
  };

  const { data } = await sb.from('verity_wrapped').upsert(wrapped, { onConflict: 'user_id,year' }).select().single();
  return data ?? wrapped;
}
